Repository slateci/slate-client-server, pull requests merged in 2022-08, with the labels that each got.

#254 Feature/253 write a build aws c++ sdk GitHub action
  .github/workflows/aws-cpp-sdk.yml
Labels: enhancement

#256 Dockerfile now uses pre-built aws c++ sdk and slate-client-server:1.0.9.
  resources/docker/Dockerfile
Labels: enhancement

#258 Minor cleanups and refactoring
  include/client/Client.h
  src/ClusterCommands.cpp
  src/KubeInterface.cpp
  src/client/Client.cpp
  src/client/ClusterRegistration.cpp
  test/DBServer.cpp
Labels: enhancement

#259 Feature/250 new GitHub workflow for api unit tests
  .github/workflows/unit-tests.yml
Labels: enhancement

#260 Federation controller support, Ingress, and unit tests
  .github/workflows/aws-cpp-sdk.yml
  .github/workflows/pr.yml
  .github/workflows/unit-tests.yml
  include/client/Client.h
  resources/TESTING_SETUP.md
  resources/docker/Dockerfile
  resources/docker/clion_remote.Dockerfile
  src/ApplicationInstanceCommands.cpp
  src/ClusterCommands.cpp
  src/KubeInterface.cpp
  src/client/Client.cpp
  src/client/ClusterRegistration.cpp
  src/client/cluster_components/FederationRBAC.cpp
  src/client/cluster_components/IngressController.cpp
  test/DBServer.cpp
  test/TestApplicationInstall.cpp
  test/test_main.cpp
Labels: bug, enhancement

#262 Updated client download link in client_manual.md
  resources/docs/client_manual.md
Labels: enhancement

#263 Updated client download link in client_manual.md (#262)
  resources/docs/client_manual.md
Labels: enhancement

#265 Update install urls to the correct version
  src/client/ClusterRegistration.cpp
Labels: bug, client

#266 Client update: Update install urls to the correct version (#265)
  src/client/ClusterRegistration.cpp
Labels: bug, client

#268 Disable yaml cpp tests
  test/TestApplicationInstall.cpp
Labels: enhancement

#269 Disabling yaml-cpp - related unit test
  resources/docker/clion_remote.Dockerfile
  test/TestApplicationInstall.cpp
Labels: enhancement
