Repository slateci/slate-client-server, pull requests merged in 2022-10, with the labels that each got.

#299 Fixes for the ingress controller based on working meeting
  resources/nginx-ingress.yaml
  src/client/cluster_components/IngressController.cpp
Labels: bug

#300 Bugs and assorted updates
  .github/dependabot.yaml
  .github/workflows/deploy-client.yml
  .github/workflows/unit-tests.yml
  resources/nginx-ingress.yaml
  src/ClusterCommands.cpp
  src/client/cluster_components/IngressController.cpp
  test/TestAdHocApplicationInstall.cpp
  test/TestApplicationInstall.cpp
  test/TestClusterAllowedApplicationAddition.cpp
  test/TestClusterAllowedApplicationDeletion.cpp
  test/TestClusterAllowedApplicationListing.cpp
  test/TestClusterAllowedGroupAddition.cpp
  test/TestClusterAllowedGroupChecking.cpp
  test/TestClusterAllowedGroupDeletion.cpp
  test/TestClusterAllowedGroupListing.cpp
  test/TestClusterCreation.cpp
  test/TestClusterDeletion.cpp
  test/TestClusterInfo.cpp
  test/TestClusterListing.cpp
  test/TestClusterUpdate.cpp
  test/TestGroupClusterListing.cpp
  test/TestGroupDeletion.cpp
  test/TestInstanceDeletion.cpp
  test/TestInstanceDuplicates.cpp
  test/TestInstanceInfoFetching.cpp
  test/TestInstanceListing.cpp
  test/TestInstanceRestarting.cpp
  test/TestInstanceScale.cpp
  test/TestMonitoringCredentialAllocation.cpp
  test/TestSecretCreation.cpp
  test/TestSecretDeletion.cpp
  test/TestSecretFetching.cpp
  test/TestSecretListing.cpp
  test/TestVolumeCreation.cpp
  test/TestVolumeDeletion.cpp
  test/TestVolumeInfo.cpp
  test/TestVolumeListing.cpp
  test/test.h
  test/test_main.cpp
Labels: bug, enhancement

#309 Feature/308 move deploy clientyml GitHub workflow to slatecigithub actions
  .github/workflows/deploy-client.yml
  .github/workflows/deploy.yml
Labels: enhancement

#312 Updated prod/secrets.yml to use rev. 4 of associated GCP secret.
  resources/chart/vars/prod/secrets.yml
Labels: bug, server

#314 Feature/313 slate client v1031 doesnt work on macos 120
  .github/workflows/deploy-client.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  .github/workflows/pr-chart.yml
  .github/workflows/pr-image.yml
  .github/workflows/unit-tests.yml
Labels: enhancement
