Repository slateci/slate-client-server, pull requests merged in 2022-09, with the labels that each got.

#272 Updated deploy-client.yml github workfow with slate-client-alpine:1.1.0.
  .github/workflows/deploy-client.yml
Labels: enhancement

#273 Yaml client fix
  CMakeLists.txt
  include/Utilities.h
  include/client/Client.h
  src/ClusterCommands.cpp
  src/Utilities.cpp
  src/client/Client.cpp
  src/client/ClusterRegistration.cpp
Labels: bug

#274 Don't do string substitutions
  src/client/Client.cpp
Labels: bug

#275 Yaml client fix
  src/ClusterCommands.cpp
Labels: bug

#276 Make sure to pass namespace to api server in request
  src/ClusterCommands.cpp
  src/client/Client.cpp
Labels: bug

#277 Yaml client fix
  src/ClusterCommands.cpp
Labels: bug

#285 Unable to parse kubeconfig as YAML
  .github/workflows/deploy-client.yml
  CMakeLists.txt
  include/Utilities.h
  include/client/Client.h
  src/ApplicationInstanceCommands.cpp
  src/ClusterCommands.cpp
  src/Utilities.cpp
  src/client/Client.cpp
  src/client/ClusterRegistration.cpp
Labels: bug, client, server

#287 New crontab for unit-tests.yml github workflow.
  .github/workflows/unit-tests.yml
Labels: enhancement

#289 Added pre-release bool to deploy-client.yml github workflow.
  .github/workflows/deploy-client.yml
Labels: enhancement

#290 GitHub Action updates
  .github/workflows/deploy-client.yml
  .github/workflows/unit-tests.yml
Labels: enhancement

#292 Fix cluster creation in tests
  src/ClusterCommands.cpp
  test/TestAdHocApplicationInstall.cpp
  test/TestApplicationInstall.cpp
  test/TestClusterAllowedApplicationAddition.cpp
  test/TestClusterAllowedApplicationDeletion.cpp
  test/TestClusterAllowedApplicationListing.cpp
  test/TestClusterAllowedGroupAddition.cpp
  test/TestClusterAllowedGroupChecking.cpp
  test/TestClusterAllowedGroupDeletion.cpp
  test/TestClusterAllowedGroupListing.cpp
  test/TestClusterCreation.cpp
  test/TestClusterDeletion.cpp
  test/TestClusterInfo.cpp
  test/TestClusterListing.cpp
  test/TestClusterUpdate.cpp
  test/TestGroupClusterListing.cpp
  test/TestGroupDeletion.cpp
  test/TestInstanceDeletion.cpp
  test/TestInstanceDuplicates.cpp
  test/TestInstanceInfoFetching.cpp
  test/TestInstanceListing.cpp
  test/TestInstanceRestarting.cpp
  test/TestInstanceScale.cpp
  test/TestMonitoringCredentialAllocation.cpp
  test/TestSecretCreation.cpp
  test/TestSecretDeletion.cpp
  test/TestSecretFetching.cpp
  test/TestSecretListing.cpp
  test/TestVolumeCreation.cpp
  test/TestVolumeDeletion.cpp
  test/TestVolumeInfo.cpp
  test/TestVolumeListing.cpp
  test/test.h
  test/test_main.cpp
Labels: bug, client, server

#293 Added Slack notifications to deploy-client and unit-tests github work…
  .github/workflows/deploy-client.yml
  .github/workflows/unit-tests.yml
Labels: enhancement

#297 Commented out other k8s versions in unit-tests.yml github workflow.
  .github/workflows/unit-tests.yml
Labels: enhancement
