Repository slateci/slate-client-server, pull requests merged in 2022-05, with the labels that each got.

#192 Added -p option to mkdir build.
  README.md
  resources/rpm_specs/aws-sdk-cpp.spec
  resources/rpm_specs/slate-api-server.spec
  resources/rpm_specs/slate-client.spec
Labels: bug

#193 Assorted bug fixes and latest Docker development
  .github/workflows/docker-lint-scan.yml
  .github/workflows/slate-api.yml
  README.md
  docker-compose.yml
  resources/docker/Dockerfile
  resources/docker/scripts/docker-entrypoint.sh
  resources/rpm_specs/aws-sdk-cpp.spec
  resources/rpm_specs/slate-api-server.spec
  resources/rpm_specs/slate-client.spec
  src/client/ClusterRegistration.cpp
Labels: bug, enhancement

#196 Removed linux-specific bind-mounts.
  docker-compose.yml
  resources/docs/docker_compose.md
Labels: bug

#197 Get baseDomain name and helm repo url from config file
  include/PersistentStore.h
  src/PersistentStore.cpp
  src/slate_service.cpp
  test/test_main.cpp
Labels: enhancement

#200 Added other documented config vars.
  docker-compose.yml
  resources/docker/conf/slate.conf
Labels: enhancement

#205 Added VERSION_OVERRIDE to cmake.
  cmake/extract_version.sh
  resources/docker/Dockerfile
  resources/docker/scripts/build.sh
  resources/docker/scripts/init/api.sh
Labels: bug

#206 Feature/185 move slate remote client binary build entirely into GitHub
  .github/workflows/deploy-client.yml
Labels: enhancement, client

#202 Dockerfile release-stage now installs AWS C++ SDK from source.
  resources/docker/Dockerfile
  resources/docker/yum.repos.d/aws-sdk.repo
Labels: enhancement, server

#209 Use separate config params for the helm repos
  resources/docker/conf/slate.conf
  src/slate_service.cpp
Labels: enhancement, server

#213 Added client build info to docker_compose.md.
  resources/docs/docker_compose.md
Labels: enhancement

#211 Feature/210 build static not dynamic slate remote client binaries
  .github/workflows/deploy-client.yml
Labels: bug, client
