Repository slateci/slate-client-server, pull requests merged in 2023-01, with the labels that each got.

#400 Update caches to only have 128 entries by default
  include/PersistentStore.h
  include/concurrent_multimap.h
  src/PersistentStore.cpp
Labels: enhancement

#402 401 chart remove resource request and primus api node pool
  resources/chart/templates/deployment.yml
Labels: enhancement

#404 Bumped github-actions refs to v13.
  .github/attic/pr-client.yml
  .github/workflows/aws-cpp-sdk.yml
  .github/workflows/deploy-client.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  .github/workflows/otel-cpp-client.yml
  .github/workflows/pr-chart.yml
  .github/workflows/pr-image.yml
  .github/workflows/unit-tests.yml
Labels: enhancement

#405 Update location to point to gke collector
  resources/chart/vars/values.yml
Labels: enhancement

#407 Fix for incorrect column display when listing instances
  src/ApplicationInstanceCommands.cpp
Labels: bug

#408 Gke opentel
  resources/chart/vars/values.yml
Labels: infrastructure

#409 Opentel additions
  include/Telemetry.h
  src/ApplicationCommands.cpp
  src/ApplicationInstanceCommands.cpp
  src/ClusterCommands.cpp
  src/GroupCommands.cpp
  src/KubeInterface.cpp
  src/MonitoringCredentialCommands.cpp
  src/PersistentStore.cpp
  src/SecretCommands.cpp
  src/Telemetry.cpp
  src/UserCommands.cpp
  src/VersionCommands.cpp
  src/VolumeClaimCommands.cpp
  src/slate_service.cpp
Labels: bug, enhancement

#386 Feature/330 integrate unit tests with a widely supported framework
  CMakeLists.txt
  include/Utilities.h
  include/catch/catch.hpp
  src/ApplicationCommands.cpp
  src/ClusterCommands.cpp
  src/GroupCommands.cpp
  src/Utilities.cpp
  src/client/Client.cpp
  test2/CMakeLists.txt
  test2/main.cpp
  test2/unit_tests.cpp
Labels: enhancement

#418 Use CTest for new tests
  CMakeLists.txt
  include/catch/catch.hpp
  test/TestUtility.cpp
  test2/CMakeLists.txt
  test2/main.cpp
  test2/unit_tests.cpp
Labels: bug, client

#421 Fix unit tests
  src/ApplicationCommands.cpp
  src/Archive.cpp
  test/TestAdHocApplicationInstall.cpp
Labels: bug
