Repository slateci/slate-client-server, pull requests merged in 2023-03, with the labels that each got.

#441 Incremented github-actions refs to v15 in workflow files.
  .github/workflows/aws-cpp-sdk.yml
  .github/workflows/deploy-client.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  .github/workflows/otel-cpp-client.yml
  .github/workflows/pr-chart.yml
  .github/workflows/pr-client.yml
  .github/workflows/pr-image.yml
  .github/workflows/unit-tests.yml
Labels: infrastructure

#443 Fix references to v1alpha2
  src/KubeInterface.cpp
  src/client/ClusterRegistration.cpp
  test/DBServer.cpp
Labels: bug

#445 Updated client pre/release refs in github workflow files.
  .github/workflows/deploy-client.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
Labels: enhancement

#446 Fix ns operations
  src/DNSManipulator.cpp
  src/client/Client.cpp
  src/client/ClusterRegistration.cpp
Labels: bug

#447 Redo v1alpha2 version change
  src/KubeInterface.cpp
  src/client/ClusterRegistration.cpp
  test/DBServer.cpp
Labels: bug

#452 Fix whitespace
  include/ApplicationInstanceCommands.h
  include/ClusterCommands.h
  include/FileSystem.h
  include/HTTPRequests.h
  include/KubeInterface.h
  include/MonitoringCredentialCommands.h
  include/PersistentStore.h
  include/Process.h
  include/SecretCommands.h
  include/ServerUtilities.h
  include/Telemetry.h
  include/UserCommands.h
  include/client/Client.h
  src/ApplicationCommands.cpp
  src/ApplicationInstanceCommands.cpp
  src/Archive.cpp
  src/ClusterCommands.cpp
  src/GroupCommands.cpp
  src/HTTPRequests.cpp
  src/KubeInterface.cpp
  src/MonitoringCredentialCommands.cpp
  src/PersistentStore.cpp
  src/Process.cpp
  src/SecretCommands.cpp
  src/ServerUtilities.cpp
  src/Utilities.cpp
  src/client/Client.cpp
  src/client/ClusterRegistration.cpp
  src/client/slate_client.cpp
  src/slate_service.cpp
  test/TestClusterCreation.cpp
  test/TestInstanceDuplicates.cpp
  test/TestInstanceScale.cpp
  test/TestUserListing.cpp
  test/TestVolumeListing.cpp
  test/test.h
  test/test_main.cpp
Labels: enhancement
